export class Coupons {
    id?:string;
    name?:string;
    description?:string;
    imageCoupon?:string;
    idtypeOfCoupon?:string;
    nameTypeOfCoupon?:string;
    state?:string[];
    createDate?:string[];
    expirationDate?:string[];
    codeToRedeem?:string;
    termsAndConditions?:string;
    idAllies?:string;
    nameAllies?:string;
    idHeadquarters?:string;
    nameHeadquarters?:string;
    idDishes?:string;
    nameDishes?:string;
    numberOfUnits?:number;
    discountRate?:number;
    creationTime?:string[];
    expirationTime?:string[];
    codeReferred?:string;
}