export class Coupons {
    id?:string;
    name?:string;
    description?:string;
    imageCoupon?:string;
    idtypeOfCoupon?:string;
    nameTypeOfCoupon?:string;
    state?:boolean;
    createDate?:Date;
    expirationDate?:Date;
    codeToRedeem?:string;
    termsAndConditions?:string;
    idAllies?:string;
    nameAllies?:string;
    idHeadquarters?:string;
    nameHeadquarters?:string;
    idDishes?:string;
    nameDishes?:string;
    numberOfUnits?:number;
    discountRate?:number;
    creationTime?:Date;
    expirationTime?:Date;
    codeReferred?:string;
}