export class Headquarters {
    id?:string;
    idAllies?:string;
    nameAllies?:string;
    name?:string;
    ubication?:string;
    address?:string;
    numberFloor?:string;
    local?:string;
    generalContact?:string;
    chargeGC?:string;
    mobileGC?:string;
    telephoneGC?:string;
    principarlServices?:string[];
    costPerService?:number;
    aditionalServices?:string[];
    averageDeliveryTime?:string;
    headquartersContact?:string;
    chargeHC?:string;
    mobileHC?:string;
    telephoneHC?:string;
    emailHC?:string;
}