export class Pqrs {
    id?:string;
    date?:String;
    idUser?:string;
    nameUser?:string;
    lastNameUser?:string;
    email?:string;
    gender?:string;
    birthday?:String;
    phone?:string;
    idAllies?:string;
    nameAllie?:string;
    idHeadquarter?:string;
    nameHeadquarter?:string;
    state?:boolean;
    description?:string;
    reply?:string;
    typeOfService?:string;
}