export class Profiles {
  _id?:string;
  id?:string;
  state?:string[];
  entryDate?:Date;
  modificationDate?:Date;
  numberOfModifications?:number;
  idAllies?:string;
  nameAllie?:string;
  idHeadquarter?:string;
  nameHeadquarter?:string;
  idCharge?:string;
  nameCharge?:string;
  userCode?:string;
  permis?:string;
  identification?:string;
  name?:string;
  email?:string;
  photo?:string;
  ratings?:number[];
  idFirebase?:string;
}