export class ProfileList {
    id?:string;
    state?:string[];
    entryDate?:string;
    modificationDate?:string;
    numberOfModifications?:number;
    idAllies?:string;
    nameAllie?:string;
    idHeadquarter?:string;
    nameHeadquarter?:string;
    idCharge?:string;
    nameCharge?:string;
    userCode?:string;
    permis?:string;
    identification?:string;
    name?:string;
    email?:string;
    photo?:string;
  }